# Generated by Django 3.1.2 on 2020-11-03 01:29

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('picture', models.CharField(default='pic1', max_length=100)),
                ('announcement', models.CharField(default='This is group number 1', max_length=100)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=9119119111),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.CharField(default='pic1', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='theme1', max_length=100),
        ),
    ]
