# Generated by Django 3.1.2 on 2020-11-03 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201103_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='announcement',
            field=models.CharField(default='This is a group', max_length=100),
        ),
    ]
